[package]
name = "calumma-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "calumma_ffi"
crate-type = ["staticlib", "rlib"]

[dependencies]
calumma-core = { path = "../core" }
calumma-io = { path = "../io" }
calumma-ops = { path = "../ops" }
calumma-render = { path = "../render" }
anyhow = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
parking_lot = { workspace = true }
num_enum = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true, default-features = false, features = ["metal", "wgsl"] }

[dev-dependencies]
tempfile = { workspace = true }
