[package]
name = "calumma-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
calumma-core = { path = "../core" }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true, default-features = false, features = ["metal", "wgsl"] }
pollster = { workspace = true }

[build-dependencies]
naga = { workspace = true, features = ["wgsl-in"] }
