#!/usr/bin/env python3

from __future__ import annotations

import sys
from pathlib import Path

from _helpers import (
    COLOR_KEYS,
    TOKEN_MODE_DARK,
    TOKEN_MODE_LIGHT,
    TOKENS_CPP_OUT,
    accent_pair,
    hex_to_srgb,
    load_tokens,
    token_colors,
    token_control,
    token_presets,
    token_radius,
    token_space,
    token_type,
    token_window,
)
from constants import (
    CONTROL_KEYS,
    ENCODING_UTF8,
    MSG_WROTE,
    RADIUS_KEYS,
    SPACE_KEYS,
    TYPE_KEYS,
    WINDOW_KEYS,
)


def cpp_color_lit(name: str, h: str) -> str:
    r, g, b, a = hex_to_srgb(h)
    return f"    static constexpr Color {name}{{{r:.6f}f, {g:.6f}f, {b:.6f}f, {a:.6f}f}};"


def generate_tokens_cpp() -> Path:
    tokens = load_tokens()
    radius = token_radius(tokens)
    space = token_space(tokens)
    control = token_control(tokens)
    typ = token_type(tokens)
    window = token_window(tokens)
    colors = token_colors(tokens)
    presets = token_presets(tokens)
    light = colors[TOKEN_MODE_LIGHT]
    dark = colors[TOKEN_MODE_DARK]

    lines = [
        "#pragma once",
        "",
        "// Generated by ./manage.py tokens from design/tokens.json. Do not edit by hand.",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace calumma::tokens {",
        "",
        "struct Color {",
        "    float r = 0.0f;",
        "    float g = 0.0f;",
        "    float b = 0.0f;",
        "    float a = 1.0f;",
        "",
        "    // 0xRRGGBB, the shape calm_engine_set_board_colors and the palette both use.",
        "    constexpr uint32_t packedRgb() const {",
        "        return (static_cast<uint32_t>(r * 255.0f + 0.5f) << 16) |",
        "               (static_cast<uint32_t>(g * 255.0f + 0.5f) << 8) |",
        "               static_cast<uint32_t>(b * 255.0f + 0.5f);",
        "    }",
        "};",
        "",
        "struct Preset {",
        "    std::string_view id;",
        "    std::string_view label;",
        "    int width = 0;",
        "    int height = 0;",
        "};",
        "",
        "struct Radius {",
    ]
    for key in RADIUS_KEYS:
        lines.append(f"    static constexpr float {key} = {float(radius[key])}f;")
    lines += ["};", "", "struct Space {"]
    for key in SPACE_KEYS:
        lines.append(f"    static constexpr float {key} = {float(space[key])}f;")
    lines += ["};", "", "struct Control {"]
    for key in CONTROL_KEYS:
        lines.append(f"    static constexpr float {key} = {float(control[key])}f;")
    lines += ["};", "", "struct TypeSize {"]
    for json_key, cpp_name in TYPE_KEYS:
        lines.append(f"    static constexpr float {cpp_name} = {float(typ[json_key])}f;")
    lines += ["};", "", "struct Window {"]
    for key in WINDOW_KEYS:
        lines.append(f"    static constexpr float {key} = {float(window[key])}f;")
    lines += ["};", "", "struct Light {"]
    for key in COLOR_KEYS:
        value = light[key]
        assert isinstance(value, str)
        lines.append(cpp_color_lit(key, value))
    teal, orange = accent_pair(light)
    lines.append(cpp_color_lit("accentTeal", teal))
    lines.append(cpp_color_lit("accentOrange", orange))
    lines += ["};", "", "struct Dark {"]
    for key in COLOR_KEYS:
        value = dark[key]
        assert isinstance(value, str)
        lines.append(cpp_color_lit(key, value))
    teal, orange = accent_pair(dark)
    lines.append(cpp_color_lit("accentTeal", teal))
    lines.append(cpp_color_lit("accentOrange", orange))
    lines += [
        "};",
        "",
        f"inline constexpr std::array<Preset, {len(presets)}> presets{{{{",
    ]
    for preset in presets:
        label = str(preset["label"])
        pid = label.lower().replace(" ", "-").replace(":", "")
        lines.append(
            f'    Preset{{"{pid}", "{label}", {int(preset["width"])}, {int(preset["height"])}}},'
        )
    lines += ["}};", "", "}  // namespace calumma::tokens", ""]

    TOKENS_CPP_OUT.parent.mkdir(parents=True, exist_ok=True)
    TOKENS_CPP_OUT.write_text("\n".join(lines), encoding=ENCODING_UTF8)
    return TOKENS_CPP_OUT


def main() -> int:
    out = generate_tokens_cpp()
    print(f"{MSG_WROTE} {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
