#pragma once

// Generated by ./manage.py tokens from design/tokens.json. Do not edit by hand.

#include <array>
#include <cstdint>
#include <string_view>

namespace calumma::tokens {

struct Color {
    float r = 0.0f;
    float g = 0.0f;
    float b = 0.0f;
    float a = 1.0f;

    // 0xRRGGBB, the shape calm_engine_set_board_colors and the palette both use.
    constexpr uint32_t packedRgb() const {
        return (static_cast<uint32_t>(r * 255.0f + 0.5f) << 16) |
               (static_cast<uint32_t>(g * 255.0f + 0.5f) << 8) |
               static_cast<uint32_t>(b * 255.0f + 0.5f);
    }
};

struct Preset {
    std::string_view id;
    std::string_view label;
    int width = 0;
    int height = 0;
};

struct Radius {
    static constexpr float sm = 4.0f;
    static constexpr float md = 6.0f;
    static constexpr float lg = 10.0f;
    static constexpr float window = 12.0f;
    static constexpr float island = 10.0f;
};

struct Space {
    static constexpr float xs = 4.0f;
    static constexpr float sm = 8.0f;
    static constexpr float md = 12.0f;
    static constexpr float lg = 16.0f;
    static constexpr float xl = 24.0f;
    static constexpr float xxl = 32.0f;
};

struct Control {
    static constexpr float height = 28.0f;
};

struct TypeSize {
    static constexpr float label = 10.0f;
    static constexpr float labelTracking = 0.08f;
    static constexpr float body = 13.0f;
    static constexpr float title = 15.0f;
    static constexpr float brand = 36.0f;
};

struct Window {
    static constexpr float mainWidth = 960.0f;
    static constexpr float mainHeight = 520.0f;
    static constexpr float mainMinWidth = 760.0f;
    static constexpr float mainMinHeight = 520.0f;
    static constexpr float newProjectWidth = 960.0f;
    static constexpr float newProjectHeight = 520.0f;
    static constexpr float newProjectMinWidth = 960.0f;
    static constexpr float newProjectMinHeight = 520.0f;
    static constexpr float pasteMinWidth = 200.0f;
    static constexpr float pasteMaxWidth = 420.0f;
    static constexpr float pasteMinHeight = 180.0f;
    static constexpr float pasteWidthRatio = 0.32f;
};

struct Light {
    static constexpr Color bg{0.909804f, 0.933333f, 0.949020f, 1.000000f};
    static constexpr Color surface{0.956863f, 0.968627f, 0.976471f, 1.000000f};
    static constexpr Color surfaceHover{0.886275f, 0.909804f, 0.933333f, 1.000000f};
    static constexpr Color text{0.070588f, 0.094118f, 0.109804f, 1.000000f};
    static constexpr Color textMuted{0.360784f, 0.419608f, 0.458824f, 1.000000f};
    static constexpr Color danger{0.839216f, 0.270588f, 0.270588f, 1.000000f};
    static constexpr Color desk{0.956863f, 0.968627f, 0.976471f, 1.000000f};
    static constexpr Color deskGrid{0.717647f, 0.768627f, 0.807843f, 1.000000f};
    static constexpr Color paper{1.000000f, 1.000000f, 1.000000f, 1.000000f};
    static constexpr Color paperBorder{0.058824f, 0.105882f, 0.141176f, 0.349020f};
    static constexpr Color islandBorder{0.058824f, 0.105882f, 0.141176f, 0.121569f};
    static constexpr Color controlBorder{0.058824f, 0.105882f, 0.141176f, 0.250980f};
    static constexpr Color controlFocusBorder{0.168627f, 0.721569f, 0.784314f, 0.800000f};
    static constexpr Color accentTeal{0.168627f, 0.721569f, 0.784314f, 1.000000f};
    static constexpr Color accentOrange{0.909804f, 0.529412f, 0.227451f, 1.000000f};
};

struct Dark {
    static constexpr Color bg{0.086275f, 0.109804f, 0.125490f, 1.000000f};
    static constexpr Color surface{0.101961f, 0.125490f, 0.141176f, 1.000000f};
    static constexpr Color surfaceHover{0.141176f, 0.172549f, 0.196078f, 1.000000f};
    static constexpr Color text{0.949020f, 0.960784f, 0.968627f, 1.000000f};
    static constexpr Color textMuted{0.541176f, 0.592157f, 0.627451f, 1.000000f};
    static constexpr Color danger{0.909804f, 0.352941f, 0.352941f, 1.000000f};
    static constexpr Color desk{0.039216f, 0.047059f, 0.058824f, 1.000000f};
    static constexpr Color deskGrid{0.070588f, 0.094118f, 0.125490f, 1.000000f};
    static constexpr Color paper{0.109804f, 0.141176f, 0.168627f, 1.000000f};
    static constexpr Color paperBorder{1.000000f, 1.000000f, 1.000000f, 0.349020f};
    static constexpr Color islandBorder{1.000000f, 1.000000f, 1.000000f, 0.121569f};
    static constexpr Color controlBorder{1.000000f, 1.000000f, 1.000000f, 0.200000f};
    static constexpr Color controlFocusBorder{0.235294f, 0.788235f, 0.839216f, 0.800000f};
    static constexpr Color accentTeal{0.235294f, 0.788235f, 0.839216f, 1.000000f};
    static constexpr Color accentOrange{0.941176f, 0.580392f, 0.290196f, 1.000000f};
};

inline constexpr std::array<Preset, 5> presets{{
    Preset{"169-hd", "16:9 HD", 1920, 1080},
    Preset{"square", "Square", 1080, 1080},
    Preset{"a4-portrait", "A4 Portrait", 2480, 3508},
    Preset{"a4-landscape", "A4 Landscape", 3508, 2480},
    Preset{"4k-cinema", "4K Cinema", 3840, 2160},
}};

}  // namespace calumma::tokens
