[package]
name = "calumma-io"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
calumma-core = { path = "../core" }
rayon = { workspace = true }
rusqlite = { workspace = true, features = ["bundled"] }
dirs = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
png = { workspace = true }
flate2 = { workspace = true }
rustc-hash = { workspace = true }
image = { workspace = true, features = ["jpeg", "png", "webp", "tiff", "avif", "rayon"] }
resvg = { workspace = true }
heif-rs = { workspace = true }
avif-decode = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
flate2 = { workspace = true }
