use super::{AppWindow, LayerChrome, ToolChrome};
use crate::shell::Catalog;
use slint::{ComponentHandle, SharedString};

pub const DEFAULT_WIDTH: u32 = 1280;
pub const DEFAULT_HEIGHT: u32 = 720;

pub fn init_form_defaults(ui: &AppWindow, l10n: &Catalog) {
    ui.set_project_name(SharedString::from(l10n.get("newProject")));
    ui.set_width_text(SharedString::from(DEFAULT_WIDTH.to_string()));
    ui.set_height_text(SharedString::from(DEFAULT_HEIGHT.to_string()));
    ui.set_add_guide_offset(SharedString::from("0"));
    ui.set_add_guide_horizontal(true);
}

pub fn sync_strings(ui: &AppWindow, l10n: &Catalog) {
    let put = |value: String| SharedString::from(value);

    ui.set_brand_text(put(l10n.get("brand")));
    ui.set_tagline_text(put(l10n.get("tagline")));
    ui.set_project_name_label(put(l10n.get("projectName")));
    ui.set_resolution_label(put(l10n.get("resolution")));
    ui.set_create_label(put(l10n.get("create")));
    ui.set_presets_label(put(l10n.get("presets")));
    ui.set_recents_label(put(l10n.get("recents")));
    ui.set_clear_all_label(put(l10n.get("clearAllRecents")));
    ui.set_no_recents_label(put(l10n.get("noRecents")));
    ui.set_delete_project_label(put(l10n.get("deleteProject")));
    ui.set_paste_artwork_title(put(l10n.get("pasteArtwork")));
    ui.set_paste_artwork_hint(put(l10n.get("pasteArtworkHint")));
    ui.set_artwork_formats(put(l10n.get("artworkFormats")));
    ui.set_back_to_landing_tip(put(l10n.get("backToProjects")));
    ui.set_settings_title(put(l10n.get("settings")));
    ui.set_theme_label(put(l10n.get("theme")));
    ui.set_theme_light_label(put(l10n.get("themeLight")));
    ui.set_theme_dark_label(put(l10n.get("themeDark")));
    ui.set_language_label(put(l10n.get("language")));
    ui.set_language_name(put(l10n.get("languageEnglish")));
    ui.set_memory_label(put(l10n.get("memoryUsed")));
    ui.set_version_label(put(l10n.get("version")));
    ui.set_color_label(put(l10n.get("color")));
    ui.set_primary_color_label(put(l10n.get("primaryColor")));
    ui.set_secondary_color_label(put(l10n.get("secondaryColor")));
    ui.set_tertiary_color_label(put(l10n.get("tertiaryColor")));
    ui.set_file_menu_title(put(l10n.get("fileMenu")));
    ui.set_edit_menu_title(put(l10n.get("editMenu")));
    ui.set_board_menu_title(put(l10n.get("boardMenu")));
    ui.set_new_project_menu_title(put(l10n.get("newProjectMenu")));
    ui.set_undo_menu_title(put(l10n.get("undo")));
    ui.set_redo_menu_title(put(l10n.get("redo")));
    ui.set_fit_view_menu_title(put(l10n.get("fitToView")));
    ui.set_fit_view_label(put(l10n.get("fitToView")));
    ui.set_zoom_in_label(put(l10n.get("zoomIn")));
    ui.set_zoom_out_label(put(l10n.get("zoomOut")));
    ui.set_toggle_layers_menu_title(put(l10n.get("toggleLayers")));
    ui.set_guides_tip(put(l10n.get("guides")));
    ui.set_guides_title(put(l10n.get("guides")));
    ui.set_guides_hint(put(l10n.get("guidesHint")));
    ui.set_no_guides_label(put(l10n.get("noGuides")));
    ui.set_add_guide_label(put(l10n.get("addGuide")));
    ui.set_guides_full_label(put(l10n.get("guidesFull")));
    ui.set_guide_top_label(put(l10n.get("guideTop")));
    ui.set_guide_left_label(put(l10n.get("guideLeft")));
    ui.set_delete_guide_tip(put(l10n.get("deleteGuide")));
    ui.set_clear_guides_label(put(l10n.get("clearGuides")));
    ui.set_fullscreen_menu_title(put(l10n.get("enterFullScreen")));
    ui.set_layers_title(put(l10n.get("layers")));
    ui.set_add_layer_label(put(l10n.get("addLayer")));
    ui.set_bounds_label(put(l10n.get("layerBounds")));
    ui.set_bounds_x_label(put(l10n.get("layerBoundsX")));
    ui.set_bounds_y_label(put(l10n.get("layerBoundsY")));
    ui.set_width_short_label(put(l10n.get("canvasWidth")));
    ui.set_height_short_label(put(l10n.get("canvasHeight")));
    ui.set_export_menu_title(put(l10n.get("exportMenu")));
    ui.set_export_png_title(put(l10n.format("exportAs", &["PNG"])));
    ui.set_export_jpeg_title(put(l10n.format("exportAs", &["JPEG"])));
    ui.set_export_webp_title(put(l10n.format("exportAs", &["WebP"])));
    ui.set_export_avif_title(put(l10n.format("exportAs", &["AVIF"])));
    ui.set_export_heic_title(put(l10n.format("exportAs", &["HEIC"])));
    ui.set_export_psd_title(put(l10n.format("exportAs", &["PSD"])));
    ui.set_export_svg_title(put(l10n.format("exportAs", &["SVG"])));
    ui.set_export_pdf_title(put(l10n.format("exportAs", &["PDF"])));
    ui.set_tools_menu_title(put(l10n.get("smartTools")));
    ui.set_upscale_label(put(l10n.get("upscale")));
    ui.set_seam_carve_label(put(l10n.get("seamCarve")));
    ui.set_layer_settings_label(put(l10n.get("layerSettings")));
    ui.set_layer_export_label(put(l10n.get("exportLayer")));
    ui.set_layer_duplicate_label(put(l10n.get("duplicateLayer")));
    ui.set_layer_delete_label(put(l10n.get("deleteLayer")));
    ui.set_layer_visibility_label(put(l10n.get("layerVisibility")));
    ui.set_opacity_label(put(l10n.get("opacity")));

    let chrome = ui.global::<ToolChrome>();
    chrome.set_brush_size_label(put(l10n.get("brushSize")));
    chrome.set_ink_opacity_label(put(l10n.get("inkOpacity")));
    chrome.set_blur_label(put(l10n.get("blurStrength")));
    chrome.set_hardness_label(put(l10n.get("eraserHardness")));
    chrome.set_tolerance_label(put(l10n.get("tolerance")));
    chrome.set_sample_label(put(l10n.get("sampleSize")));
    chrome.set_fill_label(put(l10n.get("fill")));
    chrome.set_stroke_label(put(l10n.get("stroke")));
    chrome.set_vector_label(put(l10n.get("vectorMode")));
    chrome.set_aligned_label(put(l10n.get("cloneAligned")));
    chrome.set_transform_label(put(l10n.get("toolTransform")));
    chrome.set_crop_aspect_label(put(l10n.get("cropAspectRatio")));
    chrome.set_crop_overlay_label(put(l10n.get("cropOverlay")));
    chrome.set_crop_free_label(put(l10n.get("cropAspectFree")));
    chrome.set_crop_square_label(put("1:1".into()));
    chrome.set_crop_overlay_off_label(put(l10n.get("cropOverlayOff")));
    chrome.set_crop_overlay_thirds_label(put(l10n.get("cropOverlayThirds")));
    chrome.set_crop_overlay_grid_label(put(l10n.get("cropOverlayGrid")));
    chrome.set_crop_overlay_diagonal_label(put(l10n.get("cropOverlayDiagonal")));
    chrome.set_crop_overlay_golden_label(put(l10n.get("cropOverlayGoldenRatio")));
    chrome.set_crop_cancel_label(put(l10n.get("cropCancel")));
    chrome.set_crop_commit_label(put(l10n.get("cropCommit")));

    let layers = ui.global::<LayerChrome>();
    layers.set_visibility_label(put(l10n.get("layerVisibility")));
    layers.set_opacity_label(put(l10n.get("opacity")));
    layers.set_blend_label(put(l10n.get("blendMode")));
    layers.set_blend_normal_label(put(l10n.get("blendNormal")));
    layers.set_blend_multiply_label(put(l10n.get("blendMultiply")));
    layers.set_blend_screen_label(put(l10n.get("blendScreen")));
    layers.set_filters_label(put(l10n.get("filters")));
    layers.set_brightness_label(put(l10n.get("brightness")));
    layers.set_contrast_label(put(l10n.get("contrast")));
    layers.set_vibrance_label(put(l10n.get("vibrance")));
    layers.set_saturation_label(put(l10n.get("saturation")));
    layers.set_gamma_label(put(l10n.get("levelsGamma")));
    layers.set_reset_filters_label(put(l10n.get("resetFilters")));
    layers.set_rename_label(put(l10n.get("renameLayer")));
    layers.set_flatten_label(put(l10n.get("flattenClippingMask")));
    layers.set_merge_label(put(l10n.get("mergeLayerDown")));
    layers.set_reset_transform_label(put(l10n.get("resetTransform")));
    layers.set_move_up_label(put(l10n.get("moveLayerUp")));
    layers.set_move_down_label(put(l10n.get("moveLayerDown")));
    layers.set_rasterize_label(put(l10n.get("rasterizeLayer")));
    layers.set_export_label(put(l10n.get("exportLayer")));
    layers.set_duplicate_label(put(l10n.get("duplicateLayer")));
    layers.set_delete_label(put(l10n.get("deleteLayer")));
}
