[package]
name = "calumma-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
calumma-text = { path = "../text" }
uuid = { workspace = true, features = ["v4"] }
rayon = { workspace = true }
parking_lot = { workspace = true }
num_enum = { workspace = true }
rustc-hash = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
