import { Theme } from "calm/CalmTheme.slint";
import { Tokens } from "calm/CalmTokens.slint";
import { ProjectForm } from "project-form.slint";
import { ProjectChrome } from "project-chrome.slint";

export component Landing inherits Rectangle {
    background: Theme.bg;

    ProjectForm {
        y: Tokens.titlebar-height;
        width: 100%;
        height: parent.height - Tokens.titlebar-height;
        create-clicked => {
            ProjectChrome.create-project();
        }
    }
}
